name: 'Run SSH4Me'
on:
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ./ssh-server.sh
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run SSH4Me Action
        uses: Jisan09/SSH4Me@main
        env:
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
          USER_PASS: ${{ secrets.USER_PASS }}

name: Don't kill instace
       if: ${{ failure() }}
       run: sleep 1h 
       # Prevent to killing instance after failure
